# Generated by Django 3.1.2 on 2020-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=1, verbose_name='角色(0-管理员，1-用户，2、商家)'),
            preserve_default=False,
        ),
    ]
