# Generated by Django 3.1.2 on 2020-12-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201204_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(0, '管理员'), (1, '用户'), (2, '商家')], max_length=1, verbose_name='角色(0-管理员，1-用户，2、商家)'),
        ),
    ]
