# Generated by Django 3.1.2 on 2020-12-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='所属用户')),
                ('restaurant', models.IntegerField(verbose_name='所属餐馆')),
                ('datetime', models.DateTimeField(verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'tb_collection',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.IntegerField(verbose_name='所属餐馆')),
                ('name', models.CharField(max_length=20, verbose_name='菜品名称')),
                ('picture', models.CharField(max_length=400, verbose_name='菜品封面图片')),
                ('recommendations', models.IntegerField(verbose_name='推荐数')),
                ('price', models.FloatField(verbose_name='单价')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tb_menu',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=400, verbose_name='餐馆封面图片')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'tb_pictures',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=20, unique=True, verbose_name='餐馆名称')),
                ('owner', models.IntegerField(verbose_name='餐馆创建者')),
                ('res_address', models.CharField(max_length=200, unique=True, verbose_name='餐馆地址')),
                ('picture', models.CharField(max_length=400, verbose_name='餐馆封面图片')),
                ('score', models.FloatField(verbose_name='餐馆评分')),
                ('business_time', models.CharField(max_length=100, verbose_name='营业时间')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('verify', models.CharField(max_length=1, verbose_name='审核状态(0-审核中，1-审核通过，-1-审核未通过)')),
            ],
            options={
                'verbose_name': '餐馆',
                'verbose_name_plural': '餐馆',
                'db_table': 'tb_restaurant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='所属用户')),
                ('restaurant', models.IntegerField(verbose_name='所属餐馆')),
                ('datetime', models.DateTimeField(verbose_name='评论时间')),
                ('text', models.CharField(max_length=1000, verbose_name='评论内容')),
                ('score', models.FloatField(verbose_name='餐馆评分')),
                ('depend', models.IntegerField(default=-1, verbose_name='从属评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'tb_review',
            },
        ),
    ]
