# Generated by Django 3.1.2 on 2020-12-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='owner',
            field=models.CharField(choices=[(1, '餐馆图片'), (2, '菜单图片'), (3, '评论图片')], default=1, max_length=1, verbose_name='图片创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='verify',
            field=models.CharField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核未通过')], max_length=1, verbose_name='审核状态(0-审核中，1-审核通过，-1-审核未通过)'),
        ),
    ]
