# Generated by Django 3.1.2 on 2020-12-06 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_auto_20201204_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_restaurant', to='restaurant.restaurant', verbose_name='所属餐馆'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_owner', to=settings.AUTH_USER_MODEL, verbose_name='评论发布者'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.CharField(max_length=400, null=True, verbose_name='菜品封面图片'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='recommendations',
            field=models.IntegerField(default=0, verbose_name='推荐数'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_restaurant', to='restaurant.restaurant', verbose_name='所属餐馆'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_time',
            field=models.CharField(max_length=100, null=True, verbose_name='营业时间'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL, verbose_name='餐馆创建者'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.CharField(max_length=400, null=True, verbose_name='餐馆封面图片'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.FloatField(default=0, verbose_name='餐馆评分'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_restaurant', to='restaurant.restaurant', verbose_name='所属餐馆'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_owner', to=settings.AUTH_USER_MODEL, verbose_name='评论发布者'),
        ),
    ]
