# Generated by Django 3.1.2 on 2020-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='res_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='餐馆名称'),
        ),
    ]
