# Generated by Django 3.1.2 on 2020-12-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20201221_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='restaurant',
            field=models.ManyToManyField(related_name='tag', to='restaurant.Restaurant', verbose_name='对应餐馆'),
        ),
    ]
