# Generated by Django 3.1.2 on 2020-12-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20201222_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.IntegerField(choices=[(1, '种类'), (2, '地区')], default=1, verbose_name='标签种类'),
            preserve_default=False,
        ),
    ]
