# Generated by Django 3.1.2 on 2020-12-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_tag_tag_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='owner',
        ),
        migrations.AddField(
            model_name='pictures',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='图片所属者ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pictures',
            name='owner_type',
            field=models.CharField(choices=[('1', '餐馆图片'), ('2', '菜单图片'), ('3', '评论图片')], default=0, max_length=1, verbose_name='图片所属者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='verify',
            field=models.CharField(choices=[('0', '审核中'), ('1', '审核通过'), ('2', '审核未通过')], default='0', max_length=2, verbose_name='审核状态(0-审核中，1-审核通过，2-审核未通过)'),
        ),
    ]
