# Generated by Django 3.1.2 on 2020-12-25 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0009_auto_20201225_1326'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='collection',
            index_together={('user', 'restaurant')},
        ),
    ]
