# Generated by Django 3.1.2 on 2020-12-25 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0010_auto_20201225_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'restaurant')},
        ),
    ]
