# Generated by Django 3.1.2 on 2020-12-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20201225_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant', verbose_name='餐馆封面图片'),
        ),
    ]
