# Generated by Django 3.1.3 on 2021-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20201227_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu', verbose_name='菜品封面图片'),
        ),
    ]
