# Generated by Django 3.1.3 on 2021-01-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20210109_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='单价'),
        ),
    ]
