# Generated by Django 3.1.3 on 2021-01-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20210110_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=20, verbose_name='菜品名称'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('name', 'restaurant')},
        ),
        migrations.AlterIndexTogether(
            name='menu',
            index_together={('name', 'restaurant')},
        ),
    ]
