# Generated by Django 3.1.3 on 2021-01-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_auto_20210110_1341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='menu',
            index_together={('restaurant', 'name')},
        ),
    ]
