# Generated by Django 3.1.3 on 2021-01-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20210110_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(verbose_name='餐馆评分'),
        ),
    ]
