# Generated by Django 3.1.3 on 2021-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_auto_20210110_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(verbose_name='餐馆评分'),
        ),
    ]
