# Generated by Django 3.1.3 on 2021-01-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_auto_20210110_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(verbose_name='餐馆评分'),
        ),
    ]
