# Generated by Django 3.1.3 on 2021-01-11 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_auto_20210110_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='meal_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='就餐时间'),
            preserve_default=False,
        ),
    ]
