# Generated by Django 3.1.3 on 2021-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_review_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='meal_time',
            field=models.CharField(max_length=100, verbose_name='就餐时间'),
        ),
    ]
