# Generated by Django 3.1.3 on 2021-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_review_analyze_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='analyze_result',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='AI分析结果'),
        ),
    ]
